# Generated by Django 2.0.5 on 2018-05-04 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_auto_20180316_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrences', models.IntegerField(default=0)),
                ('frequency', models.FloatField(default=0)),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='core.Manifestation')),
            ],
            options={
                'verbose_name': 'Manifestation Token',
                'verbose_name_plural': 'Manifestation Tokens',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(max_length=255, unique=True)),
                ('_originals', models.TextField(default='{}')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.AddField(
            model_name='manifestationtoken',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestations', to='nlp.Token'),
        ),
    ]
