# Generated by Django 2.0.5 on 2018-05-29 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180316_1054'),
        ('nlp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('token', 'Token'), ('author', 'Author'), ('manifestation', 'Manifestation')], max_length=13)),
                ('stem', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_id', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('_data', models.TextField(blank=True, null=True)),
                ('manifestation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ManifestationType')),
            ],
            options={
                'verbose_name': 'Token Analysis',
                'verbose_name_plural': 'Token Analysiss',
            },
        ),
        migrations.AlterModelOptions(
            name='manifestationtoken',
            options={'ordering': ['-occurrences'], 'verbose_name': 'Manifestation Token', 'verbose_name_plural': 'Manifestation Tokens'},
        ),
        migrations.AlterUniqueTogether(
            name='analysis',
            unique_together={('start_date', 'end_date', 'analysis_type', 'manifestation_type')},
        ),
    ]
