# Generated by Django 2.0.6 on 2018-06-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0002_auto_20180529_1347'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analysis',
            unique_together=set(),
        ),
    ]
