# Generated by Django 2.0.5 on 2018-06-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('nlp', '0003_auto_20180530_1527'), ('nlp', '0004_auto_20180530_1527')]

    dependencies = [
        ('nlp', '0002_auto_20180529_1347'),
        ('core', '0009_auto_20180316_1054'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analysis',
            unique_together=set(),
        ),
    ]
