# Generated by Django 2.0.5 on 2018-06-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0003_auto_20180604_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='bigram',
            field=models.BooleanField(default=False),
        ),
    ]
