# Generated by Django 2.0.5 on 2018-06-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0004_token_bigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='algorithm',
            field=models.CharField(choices=[('unigram_bow', 'Unigram Bag of Words'), ('bigram_bow', 'Bigram Bag of Words')], default='unigram_bow', max_length=100),
            preserve_default=False,
        ),
    ]
