# Generated by Django 2.0.5 on 2018-06-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0005_analysis_algorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='stem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
