# Generated by Django 2.0.1 on 2018-01-26 18:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('author_type', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('CEP', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('means_of_access', models.CharField(blank=True, max_length=200, null=True)),
                ('manifestation_attrs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('author_attrs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('collect_attrs', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'channel',
                'verbose_name_plural': 'channels',
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to='core.Channel')),
            ],
            options={
                'verbose_name': 'collect',
                'verbose_name_plural': 'collects',
            },
        ),
        migrations.CreateModel(
            name='CollectManifestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Collect')),
            ],
        ),
        migrations.CreateModel(
            name='Manifestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_channel', models.CharField(max_length=200)),
                ('version', models.IntegerField(default=1)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestations', to='core.Channel')),
                ('collect', models.ManyToManyField(through='core.CollectManifestation', to='core.Collect')),
            ],
            options={
                'verbose_name': 'manifestation',
                'verbose_name_plural': 'manifestations',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('is_reference', models.BooleanField(default=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.Author')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.Channel')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.AddField(
            model_name='manifestation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestations', to='core.Profile'),
        ),
        migrations.AddField(
            model_name='collectmanifestation',
            name='manifestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Manifestation'),
        ),
        migrations.AlterUniqueTogether(
            name='manifestation',
            unique_together={('id_in_channel', 'version')},
        ),
    ]
