# Generated by Django 2.0.2 on 2018-02-08 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=200)),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='core.Manifestation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='core.Profile')),
            ],
            options={
                'verbose_name': 'relationship profile',
                'verbose_name_plural': 'relationship profiles',
            },
        ),
        migrations.CreateModel(
            name='RelationshipProfileAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('relationship_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='core.RelationshipProfile')),
            ],
            options={
                'verbose_name': 'relationship profile attribute',
                'verbose_name_plural': 'relationship profile attributes',
            },
        ),
        migrations.CreateModel(
            name='RelationshipProfileDomainAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('manifestation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_profile_domain_attrs', to='core.ManifestationType')),
            ],
            options={
                'verbose_name': 'Relationship Profile Domain Attribute',
                'verbose_name_plural': 'Relationship Profile Domain Attributes',
            },
        ),
    ]
