# Generated by Django 2.0.2 on 2018-02-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_relationshipprofile_relationshipprofileattribute_relationshipprofiledomainattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectattribute',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifestationattribute',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profileattribute',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='relationshipprofileattribute',
            name='value',
            field=models.TextField(),
        ),
    ]
