# Generated by Django 2.0.2 on 2018-02-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180223_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectattribute',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifestationattribute',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileattribute',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relationshipprofileattribute',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
