# Generated by Django 2.0.2 on 2018-03-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180223_1434'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='manifestation',
            unique_together={('id_in_channel', 'version', 'manifestation_type')},
        ),
    ]
