# Generated by Django 2.0.2 on 2018-03-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180301_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestationdomainattribute',
            name='is_versioned',
            field=models.BooleanField(default=False),
        ),
    ]
