# Generated by Django 2.0.2 on 2018-03-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_manifestationdomainattribute_is_versioned'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='manifestation',
            unique_together=set(),
        ),
    ]
