# Generated by Django 2.0.2 on 2018-03-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180305_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='channel'),
        ),
        migrations.AlterField(
            model_name='manifestationtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='manifestation type'),
        ),
    ]
