# Generated by Django 2.0.2 on 2018-03-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180309_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestation',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
