# Generated by Django 2.0.6 on 2018-06-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180316_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestation',
            name='collect',
            field=models.ManyToManyField(blank=True, null=True, through='core.CollectManifestation', to='core.Collect'),
        ),
    ]
